# Generated by Django 4.2.16 on 2024-12-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
