# Generated by Django 4.2.16 on 2024-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_remove_profile_user_delete_customuser_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
